gui:
    # stuff relating to the UI
    scrollHeight: 2 # how many lines you scroll by
    scrollPastBottom: true # enable scrolling past the bottom
    sidePanelWidth: 0.2 # number from 0 to 1
    expandFocusedSidePanel: false
    mainPanelSplitMode: 'flexible' # one of 'horizontal' | 'flexible' | 'vertical'
    theme:
      lightTheme: false # For terminals with a light background
      activeBorderColor:
        - green
        - bold
      inactiveBorderColor:
        - white
      optionsTextColor:
        - blue
      selectedLineBgColor:
        - reverse
      selectedRangeBgColor:
        - reverse
    commitLength:
      show: true
    mouseEvents: true
    skipUnstageLineWarning: false
    skipStashWarning: true
git:
    paging:
      colorArg: never
      pager: ydiff -p cat -s --nowrap --width={{columnWidth}}
    branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
